

server:
  port: 3081
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: customer-service
        uri: http://localhost:3001/
        predicates:
        - Path=/customer/**
      - id: hotel
        uri: http://localhost:3002/
        predicates:
        - Path=/hotel/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka
  registerWithEureka:
       - true
  fetchRegistry:
       - true
